"""报错码常量 —— 与 docs/architecture/decoupling/ERROR_CODES.md 同步。"""

# 模块 / 系统
MODULE_LOAD_FAILED = "MODULE_LOAD_FAILED"
SYSTEM_SECRET_KEY_WEAK = "SYSTEM_SECRET_KEY_WEAK"
SYSTEM_INTERNAL_ERROR = "SYSTEM_INTERNAL_ERROR"
RATE_LIMITED = "RATE_LIMITED"
VALIDATION_ERROR = "VALIDATION_ERROR"
API_ERROR = "API_ERROR"

# Agent
AGENT_MODULE_DOWN = "AGENT_MODULE_DOWN"
AGENT_LLM_UNAVAILABLE = "AGENT_LLM_UNAVAILABLE"
AGENT_MISCONFIGURED = "AGENT_MISCONFIGURED"
AGENT_TOKEN_UNSET = "AGENT_TOKEN_UNSET"
AGENT_UNAUTHORIZED = "AGENT_UNAUTHORIZED"
AGENT_PROXY_ERROR = "AGENT_PROXY_ERROR"
AGENT_SESSION_NOT_FOUND = "AGENT_SESSION_NOT_FOUND"
AGENT_SESSION_PROJECT_DENIED = "AGENT_SESSION_PROJECT_DENIED"
AGENT_INVALID_ID = "AGENT_INVALID_ID"
AGENT_CHAT_FAILED = "AGENT_CHAT_FAILED"
AGENT_ANALYZE_FAILED = "AGENT_ANALYZE_FAILED"
AGENT_IMPORT_ASSIST_FAILED = "AGENT_IMPORT_ASSIST_FAILED"
AGENT_TRENDING_FAILED = "AGENT_TRENDING_FAILED"
AGENT_CLASSIFY_FAILED = "AGENT_CLASSIFY_FAILED"
AGENT_NOTE_FAILED = "AGENT_NOTE_FAILED"
AGENT_DISPATCH_FAILED = "AGENT_DISPATCH_FAILED"
AGENT_TOOL_DENIED = "AGENT_TOOL_DENIED"
AGENT_TOOL_TIMEOUT = "AGENT_TOOL_TIMEOUT"
AGENT_TOOL_FAILED = "AGENT_TOOL_FAILED"

# LLM
LLM_KEY_MISSING = "LLM_KEY_MISSING"
LLM_DECRYPT_FAILED = "LLM_DECRYPT_FAILED"
LLM_REQUEST_FAILED = "LLM_REQUEST_FAILED"
LLM_TIMEOUT = "LLM_TIMEOUT"
LLM_RATE_LIMITED = "LLM_RATE_LIMITED"

# Graph
GRAPH_MODULE_DOWN = "GRAPH_MODULE_DOWN"
GRAPH_NOT_INDEXED = "GRAPH_NOT_INDEXED"
GRAPH_INDEX_FAILED = "GRAPH_INDEX_FAILED"
GRAPH_QUERY_FAILED = "GRAPH_QUERY_FAILED"
GRAPH_ENGINE_UNAVAILABLE = "GRAPH_ENGINE_UNAVAILABLE"
GRAPH_L1_MODULE_DOWN = "GRAPH_L1_MODULE_DOWN"

# LLM Usage
LLM_USAGE_MODULE_DOWN = "LLM_USAGE_MODULE_DOWN"

# Project / Note / Category / Tag
PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
PROJECT_URL_INVALID = "PROJECT_URL_INVALID"
PROJECT_URL_DUPLICATE = "PROJECT_URL_DUPLICATE"
PROJECT_IMPORT_FAILED = "PROJECT_IMPORT_FAILED"
NOTE_NOT_FOUND = "NOTE_NOT_FOUND"
CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
CATEGORY_PRESET_IMMUTABLE = "CATEGORY_PRESET_IMMUTABLE"
CATEGORY_NAME_DUPLICATE = "CATEGORY_NAME_DUPLICATE"
TAG_NOT_FOUND = "TAG_NOT_FOUND"
TAG_NAME_DUPLICATE = "TAG_NAME_DUPLICATE"

# GitHub
GITHUB_NOT_BOUND = "GITHUB_NOT_BOUND"
GITHUB_ACCOUNT_NOT_FOUND = "GITHUB_ACCOUNT_NOT_FOUND"
GITHUB_PAT_INVALID = "GITHUB_PAT_INVALID"
GITHUB_AUTH_FAILED = "GITHUB_AUTH_FAILED"  # 兼容；新代码优先 GITHUB_PAT_INVALID
GITHUB_API_RATE_LIMIT = "GITHUB_API_RATE_LIMIT"
GITHUB_API_FAILED = "GITHUB_API_FAILED"
GITHUB_STARS_FETCH_FAILED = "GITHUB_STARS_FETCH_FAILED"

# Profile / Settings
PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
MEMORY_PROPOSAL_NOT_FOUND = "MEMORY_PROPOSAL_NOT_FOUND"
SETTINGS_UPDATE_FAILED = "SETTINGS_UPDATE_FAILED"
SETTINGS_LLM_BASE_INVALID = "SETTINGS_LLM_BASE_INVALID"

# 全部已登记码（供测试与导出）
ALL_ERROR_CODES: frozenset[str] = frozenset(
    {
        MODULE_LOAD_FAILED,
        SYSTEM_SECRET_KEY_WEAK,
        SYSTEM_INTERNAL_ERROR,
        RATE_LIMITED,
        VALIDATION_ERROR,
        API_ERROR,
        AGENT_MODULE_DOWN,
        AGENT_LLM_UNAVAILABLE,
        AGENT_MISCONFIGURED,
        AGENT_TOKEN_UNSET,
        AGENT_UNAUTHORIZED,
        AGENT_PROXY_ERROR,
        AGENT_SESSION_NOT_FOUND,
        AGENT_SESSION_PROJECT_DENIED,
        AGENT_INVALID_ID,
        AGENT_CHAT_FAILED,
        AGENT_ANALYZE_FAILED,
        AGENT_IMPORT_ASSIST_FAILED,
        AGENT_TRENDING_FAILED,
        AGENT_CLASSIFY_FAILED,
        AGENT_NOTE_FAILED,
        AGENT_DISPATCH_FAILED,
        AGENT_TOOL_DENIED,
        AGENT_TOOL_TIMEOUT,
        AGENT_TOOL_FAILED,
        LLM_KEY_MISSING,
        LLM_DECRYPT_FAILED,
        LLM_REQUEST_FAILED,
        LLM_TIMEOUT,
        LLM_RATE_LIMITED,
        GRAPH_MODULE_DOWN,
        GRAPH_NOT_INDEXED,
        GRAPH_INDEX_FAILED,
        GRAPH_QUERY_FAILED,
        GRAPH_ENGINE_UNAVAILABLE,
        GRAPH_L1_MODULE_DOWN,
        LLM_USAGE_MODULE_DOWN,
        PROJECT_NOT_FOUND,
        PROJECT_URL_INVALID,
        PROJECT_URL_DUPLICATE,
        PROJECT_IMPORT_FAILED,
        NOTE_NOT_FOUND,
        CATEGORY_NOT_FOUND,
        CATEGORY_PRESET_IMMUTABLE,
        CATEGORY_NAME_DUPLICATE,
        TAG_NOT_FOUND,
        TAG_NAME_DUPLICATE,
        GITHUB_NOT_BOUND,
        GITHUB_ACCOUNT_NOT_FOUND,
        GITHUB_PAT_INVALID,
        GITHUB_AUTH_FAILED,
        GITHUB_API_RATE_LIMIT,
        GITHUB_API_FAILED,
        GITHUB_STARS_FETCH_FAILED,
        PROFILE_NOT_FOUND,
        MEMORY_PROPOSAL_NOT_FOUND,
        SETTINGS_UPDATE_FAILED,
        SETTINGS_LLM_BASE_INVALID,
    }
)
