"""notes 服务设置项(§8.8)。"""

from platform_settings import SettingDef, SettingType

DEFS = [
    SettingDef(key="notes.sort.default", module="notes", type=SettingType.CHOICE,
               default="updated", choices=("updated", "created", "title"),
               description="笔记默认排序"),
    SettingDef(key="notes.list.page_size", module="notes", type=SettingType.INT,
               default=100, min=10, max=500, description="列表默认条数上限"),
    SettingDef(key="notes.editor.autosave_s", module="notes", type=SettingType.INT,
               default=5, min=0, max=120, description="编辑器自动保存间隔(秒;0=关)"),
    SettingDef(key="notes.trash.retention_days", module="notes", type=SettingType.INT,
               default=30, min=0, max=365,
               description="回收站保留天数(0=永久保留;超期自动清理)"),
    SettingDef(key="notes.history.per_note", module="notes", type=SettingType.INT,
               default=20, min=0, max=100,
               description="每篇笔记保留的历史版本数(0=关闭版本历史)"),
    SettingDef(key="notes.export.dir", module="notes", type=SettingType.STR,
               default="workspace/notes-export",
               description="导出 Markdown 文件的目录"),
    SettingDef(key="notes.assets.max_mb", module="notes", type=SettingType.INT,
               default=20, min=1, max=100,
               description="单个图片附件大小上限(MB)"),
    # 仅笔记页界面偏好(与 appearance.font_scale 全站字号分离;用户按钮与 agent 同权)
    SettingDef(key="notes.ui.font_size", module="notes", type=SettingType.INT,
               default=15, min=13, max=20,
               description="笔记正文显示字号(px;仅笔记页,不影响全站)"),
    SettingDef(key="notes.ui.mode", module="notes", type=SettingType.CHOICE,
               default="edit", choices=("edit", "preview", "split"),
               description="笔记工作区视图:编辑 / 预览 / 分栏"),
    SettingDef(key="notes.ui.layout", module="notes", type=SettingType.CHOICE,
               default="list", choices=("list", "card"),
               description="笔记首页列表或卡片"),
    SettingDef(key="notes.ui.sync_scroll", module="notes", type=SettingType.BOOL,
               default=True,
               description="分栏时编辑与预览同步滚动"),
    SettingDef(key="notes.ui.list_state", module="notes", type=SettingType.CHOICE,
               default="active", choices=("active", "archived"),
               description="笔记首页显示在用或归档"),
]
